[program:gunicorn]
command=python -m gunicorn --workers 3 --timeout 120 newsite.wsgi:application
directory=/workspaces/Django_code/newDjango
autostart=true
autorestart=true
stderr_logfile=/var/log/gunicorn.err.log
stdout_logfile=/var/log/gunicorn.out.log

[program:ollama]
command=ollama serve
autostart=true
autorestart=true
stderr_logfile=/var/log/ollama.err.log
stdout_logfile=/var/log/ollama.out.log