# Generated by Django 5.2.9 on 2025-12-08 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="new_LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("llm_text", models.TextField(verbose_name="Model_name_used:")),
                ("llm_type", models.DateTimeField(verbose_name="Model_date_used:")),
            ],
        ),
        migrations.CreateModel(
            name="LLM_choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("amount", models.IntegerField(default=0)),
                (
                    "new_llm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_llm.new_llm",
                    ),
                ),
            ],
        ),
    ]
