# Generated by Django 5.2.9 on 2025-12-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_llm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new_llm",
            name="llm_text",
            field=models.CharField(max_length=200),
        ),
    ]
