# Generated by Django 5.2.9 on 2025-12-22 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_llm", "0003_convert_llm_revsrse_llm"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Revsrse_LLM",
            new_name="Reverse_LLM",
        ),
    ]
