# Generated by Django 6.0.2 on 2026-03-01 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewLLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("llm_text", models.CharField(max_length=200)),
                (
                    "llm_date_used",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date used:"
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Entry",
                "verbose_name_plural": "LLM Entries",
                "ordering": ["-llm_date_used"],
            },
        ),
        migrations.CreateModel(
            name="LLMChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("amount", models.IntegerField(default=0)),
                (
                    "new_llm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="newsite.newllm",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Choice",
                "verbose_name_plural": "LLM Choices",
            },
        ),
        migrations.CreateModel(
            name="ConvertLLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_string", models.CharField(default="", max_length=256)),
                ("new_number", models.IntegerField(blank=True, null=True)),
                (
                    "new_llm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions",
                        to="newsite.newllm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convert LLM",
                "verbose_name_plural": "Convert LLMs",
            },
        ),
        migrations.CreateModel(
            name="ReverseLLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_number", models.IntegerField(blank=True, null=True)),
                ("new_string", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "new_llm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversals",
                        to="newsite.newllm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reverse LLM",
                "verbose_name_plural": "Reverse LLMs",
            },
        ),
    ]
