# Generated by Django 6.0.2 on 2026-02-22 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Convert_LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_string", models.CharField(default="", max_length=256)),
                ("new_number", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="new_LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("llm_text", models.CharField(max_length=200)),
                (
                    "llm_date_used",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Model_date_used:",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Entry",
                "verbose_name_plural": "LLM Entries",
                "ordering": ["-llm_date_used"],
            },
        ),
        migrations.CreateModel(
            name="Reverse_LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_number", models.IntegerField()),
                ("new_string", models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LLM_choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("amount", models.IntegerField(default=0)),
                (
                    "new_llm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="newsite.new_llm",
                    ),
                ),
            ],
        ),
    ]
