# Generated by Django 5.2.9 on 2025-12-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_llm", "0002_alter_new_llm_llm_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Convert_LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_string", models.CharField(max_length=256)),
                ("new_number", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Revsrse_LLM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_number", models.IntegerField()),
                ("new_string", models.CharField(blank=True, null=True)),
            ],
        ),
    ]
