# Generated by Django 5.2.9 on 2025-12-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_llm", "0005_alter_llm_choice_new_llm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reverse_llm",
            name="new_string",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
