# Generated by Django 5.2.9 on 2025-12-22 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_llm", "0004_rename_revsrse_llm_reverse_llm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llm_choice",
            name="new_llm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="django_llm.new_llm",
            ),
        ),
    ]
